// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BNU8UiXReWuTWThehW_CCBqrhxocTnI',
    appId: '1:537131372504:android:48f548c8e4827ce003acad',
    messagingSenderId: '537131372504',
    projectId: 'scars-d81cd',
    databaseURL: 'https://scars-d81cd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scars-d81cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZO3l7YxeN96altWKdWhkFBne-krvKPM',
    appId: '1:537131372504:ios:d8ba4849dd09db3103acad',
    messagingSenderId: '537131372504',
    projectId: 'scars-d81cd',
    databaseURL: 'https://scars-d81cd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scars-d81cd.firebasestorage.app',
    iosBundleId: 'com.example.whenScarsBecomeArt',
  );
}
